### ISSUE TITLE
website speed

### ISSUE THREAD

**Issue by mnights101** [mnights101/drnights#2]
trying to get speed down to under 3 seconds
please follow recommendation on gtmetrix.com  to bring load time down. keep in mind this site is on cloudlfare and you may tweek from there as well

**Comment by brogrammersagency** [comment]
Images , JQuery, CSS Optimization done.

Extra plugins deactivated which are not using on site.
Now
PageSpeed Score   81/100  on gtmatrix
https://gtmetrix.com/reports/www.drnights.com/18YxlFgx

On google testing

Page Speed

Average 1.9s FCP2.3s DCL

Optimization    Good     85 / 100

https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.drnights.com%2F&tab=desktop

Before optimization its was 50/100 on google and 61/100 on gtmatrix.

Yesterday the site origin page builder have new version and update and I have updated it today then its conflicting with wordpress cms. So I have get back to older version of this plugin again to work fine for editing. May be soon they will update the plugin for this bug in next update then we will update it on live site.

**Comment by mnights101** [comment]
I checked gtmetrix the grade is fine but the load time is 5.8 seconds, I added cloudflare to the cdn options, yet still the page load times are not good. I see you changed to wp fastest cache, (this plugin has caused usability issue, I will monitor users to see if they complain.

Be advised I also activated rocket loader on cloudlfare. Lets give this one day to see the results

**Comment by mnights101** [comment]
In the mean time this is yslows biggest issue: expires header, can you handle that
![expires-header](https://user-images.githubusercontent.com/10249755/41070782-a0df947a-69c2-11e8-8e1b-fefe1527509d.gif)

**Comment by brogrammersagency** [comment]
I will check it and let you know.
